### PR TITLE
added code to set GIT_EXEC_PATH and the tests

### PR DESCRIPTION
**Pull request by tiff-ritz**
This is in response to [Issue 137](https://github.com/heroku/heroku-buildpack-apt/issues/137) in the [heroku-buildpack-apt](https://github.com/heroku/heroku-buildpack-apt) repo.  

If `git` is in the `project.toml` file - make sure GIT_EXEC_PATH is correctly defined after successful installation or if it is already installed.

Added unit tests

### CODE REVIEW

**Comment by tiff-ritz** [comment]
Adding each env var to the code is not a feasable approach long term.  Kept this work in a branch [in my fork](https://github.com/tiff-ritz/buildpacks-deb-packages/tree/test-indv-env)

Closing this PR and am going to open a new one with my configurable environment variable solution.

**Comment by edmorley** [comment]
> Adding each env var to the code is not a feasable approach long term

So whilst normally I would agree, I think we do need to add handling in this CNB for commonly used packages (by setting specific env vars), since otherwise it leads to poor UX if such packages don't work out of the box.

**Comment by tiff-ritz** [comment]
> > Adding each env var to the code is not a feasable approach long term
> 
> So whilst normally I would agree, I think we do need to add handling in this CNB for commonly used packages (by setting specific env vars), since otherwise it leads to poor UX if such packages don't work out of the box.

In another PR, I extended the project.toml file:

```toml
[_]
schema-version = "0.2"

[com.heroku.buildpacks.deb-packages]
install = [
    { name = "git", 
      env = { "GIT_EXEC_PATH" = "{install_dir}/usr/lib/git-core", 
              "GIT_TEMPLATE_DIR" = "{install_dir}/usr/share/git-core/templates" }
    },
    { name = "babeld" },
    { name = "ghostscript",
      skip_dependencies = true,
      force = true,
      env = { "GS_LIB" = "{install_dir}/var/lib/ghostscript" }
    },
]
```

so these can be defined per package and added after the installation.

**Comment by colincasey** [comment]
@tiff-ritz I've created an issue for this (#87) as I think we need a combination of out-of-the-box and user-provided environment configuration for installed packages.

**Pull request closed without merging**
